name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Angular CLI
        run: npm install -g @angular/cli
      - name: Install Node Modules
        run: npm install
      - name: Lint
        run: ng lint --fix

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Angular CLI
        run: npm install -g @angular/cli
      - name: Install Node Modules
        run: npm install

      - name: Run Test
        run: ng test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Angular CLI
        run: npm install -g @angular/cli
      - name: Install Node Modules
        run: npm install

      - name: Run Build
        run: ng build
