name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Angular CLI
        run: npm install -g @angular/cli@16.2.14
      - name: Install Node Modules
        run: npm install

      - name: Run Test
        run: ng test

