name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node Modules
        run: npm install

      - name: Linting
        run: ng lint

      - name: Run Test
        run: ng test

